### ISSUE TITLE
How to use it as type root

### ISSUE THREAD

**Issue by crimx** [Lusito/webextension-polyfill-ts#1]
Thanks for the great work! Is it possible to be used in `typeRoots`? I was including the polyfill as global during build process. So the IDE needs type definitions to work.

**Comment by Lusito** [comment]
Hello @crimx,

If you use NPM, it should just work. I have defined the types property in the package.json and all required .ts files are included. So unlike [web-ext-types](https://github.com/kelseasy/web-ext-types), you don't need to specify typeRoots with webextension-polyfill-ts.

If you have web-ext-types or webextension-polyfill installed, you might need to uninstall it before installing webextension-polyfill-ts .. not sure about this.

I use [Visual Studio Code](https://code.visualstudio.com/) as "IDE" (which I'd highly recommend for js/ts development) and type definitions are detected automatically. What IDE are you using? Maybe it doesn't have full support for the NPM way of defining types?

**Comment by crimx** [comment]
You need to require/import this package to let VSCode identify it right? But I include it through Webpack build process so that I don't have to do this on every file.

**Comment by Lusito** [comment]
I see. I didn't know this was possible (or anyone would use such a feature).
Do you have an example project? If I had anything to look at, I might be able to help.
It might take some time tho, since I'll by busy over the weekend with the [global game jam](https://globalgamejam.org/).

**Comment by crimx** [comment]
It is a very common pattern to gather ployfills in a separate file. In fact, that's what the create-react-app internally [does](https://github.com/facebook/create-react-app/blob/eee29075d64a4d3c2c5af4f4b9836e54e8f8bb3e/packages/react-scripts/config/webpack.config.prod.js#L67) .

Maybe you can generate the d.ts with `--declaration` and publish the `dist` to NPM instead of the whole source project. See Typescript's [docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Comment by Lusito** [comment]
I couldn't make this work in any way. I think it's because webextension-polyfill already exports a global named browser.

I will investigate if this might be fixed by generating the code that webextension-polyfill normally would from this project natively, so the dependency for webextension-polyfill would be removed and hopefully the conflict. But if that fails, I don't know how to solve this.

Feel free to try this yourself and provide a pull request. I'm not a fan of globals, so the fix needs to work using normal imports.

**Comment by crimx** [comment]
I'll see what I can do.

**Comment by crimx** [comment]
Currently types are separated from `Static` members. Is it OK if I merge them together under the `browser.[module]` namespace like [Chrome](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome/index.d.ts)?

Note: This will deprecate `imoprt { [type] } from 'webextension-polyfill-ts'`, in favor of `browser.[module].[type]`.

**Comment by crimx** [comment]
And for anonymous types, how about just keep them anonymous by copying the type definitions around without giving them names.

**Comment by Lusito** [comment]
I was not able to merge them under the browse.module namespace while still keeping the import syntax and separated files working. Feel free to give it a try.

How would you keep the anonymous types around without giving them names? inline? That is very ugly to generate readable documentation for. Aside from that it is useful to have a name for those types, so users can store attributes and variables of them in a type-checked manner.

**Comment by crimx** [comment]
Yes I meant inline. Don't you think that a "polyfill" should just be a shim for API and could be safely removed when the implementation is mature? If users need to import types from the library and use undocumented type names, wouldn't it be a strong coupling?

**Comment by Lusito** [comment]
webextension-polyfill is a polyfill.. this is a type definition "add-on". 
But ignoring this fact.. as long as web-extensions are not in a final state, which all browsers support equally (which I doubt will ever happen), there will always be the need for this kind of project.

Things like Promise polyfills can easily be replaced, because those will probably not change very much in the future. But web-extensions will probably never stop to be extended and modified to fit new needs.

Imho these inline types should never have been inlined in the first place, and I would love to see them strongly typed in future versions of webext.

Users don't **need** to use these types, but they **can**. The difference between inline and not is, that if users want to use the types when they are inlined, they would have to define them manually themselves, causing more problems when updated versions are available.

Even if they don't use them directly, they can see the typedoc documentation inside of the IDE and find out about all the properties without having to read the MDN documentation. That wouldn't be possible if they where inlined.

All in all, I think I want to keep extracting inline types, but improve the naming.. maybe define some of the names manually to improve them on a per-case basis.

**Comment by crimx** [comment]
Yeah I think you got a point. Use a notation or description to indicate a generated type name should do the job.

Since TypeScript doesn't support alias namespace, there seems to be no way to support Chrome-like namespace while keeping the module syntax.
