### ISSUE TITLE
Failed to migrate from `webextension-polyfill-ts` to `webextension-polyfill` + `@types/webextension-polyfill`

### ISSUE THREAD

**Issue by ferenc-a** [Lusito/webextension-polyfill-ts#100]
I depend on `"webextension-polyfill-ts": "^0.26.0",`, which depended on `"webextension-polyfill": "^0.8.0"`.
I tried to do the migration steps here: [link](https://github.com/Lusito/webextension-polyfill-ts#migration-guide-from-webextension-polyfill-ts). But after migration my generated code is slighly different, and breaks on runtime.
Looking through the generated, bundled JS code the main differences are using `default` instead of `browser`: like this one: `await r.browser.tabs.executeScript...` --> `await n.default.tabs.executeScript...`.
What went wrong? Are there any other steps that I should do after migrating?

**Comment by Lusito** [comment]
Hi @ferenc-a,

It's hard to tell without looking at your code or the error message you are getting. My best guess is, that your bundler or transpiler doesn't handle the import correctly. webextension-polyfill doesn't export `default`. So the new code should not contain "default" and rather be: `await n.tabs.executeScript....`.

**Comment by ferenc-a** [comment]
Thanks for the reply!
I changed `"module": "commonjs"` to `"module": "esnext"` in my tsconfig and now it seems to work. Is this a reliable fix, do you think? I'll close this, if you think so. Is commonjs not recommended nowadays?

**Comment by Lusito** [comment]
If that works for you, that is fine. esnext is the future after all.

But (there's always a catch): some node modules are not compatible yet and it's sometimes hard to make new modules play along nicely with old modules. I've had my fair share of those problems and the headaches that come with them.

So, if your setup works with module: esnext, then go for it. Just make sure the final output is compatible with your targeted browsers.

Otherwise some more fiddling with your bundler might be required.

**Comment by ferenc-a** [comment]
Thank you for the explanation!
