### ISSUE TITLE
Incompatible between browser.tabs.query and browser.tabs.update

### ISSUE THREAD

**Issue by vitalets** [Lusito/webextension-polyfill-ts#13]
Hi!
I have this code:
```ts
import { browser } from 'webextension-polyfill-ts';

async function fn() {
    const tabs = await browser.tabs.query({});
    browser.tabs.update(tabs[0].id, {active: true});
}
```
And ts shows error on `tabs[0].id`:
> TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.   Type 'undefined' is not assignable to type 'number'.

is it intended or a bug?

**Comment by Lusito** [comment]
Thanks for the report. It seems you've stumbled upon a bug on the generated files.
I'm just not sure if this affects only this method or possibly others as well.

According to this:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update

The first parameter, `tabId`, is supposed to be optional, so the code generator creates these method definitions (overloads):
```typescript
update(tabId: number, updateProperties: UpdateUpdatePropertiesType): Promise<Tab>;
update(updateProperties: UpdateUpdatePropertiesType): Promise<Tab>;
```

This is because optional parameters according to my knowledge can be left out, i.e.:
```typescript
browser.tabs.update({...});
browser.tabs.update(1, {...});
```

But after trying this in the debugger, it would seem 3 calling types are possible:
```typescript
browser.tabs.update({...});
browser.tabs.update(undefined, {...}); // same as the above
browser.tabs.update(1, {...});
```

Now I need to figure out if this is supposed to be for every optional parameter or just for some. Once I figured that out, I will supply a fix.

**Comment by Lusito** [comment]
It is worth mentioning, however, that passing undefined as first parameter to tabs.update results in the active tab being modified, which might not be what you intended. In some cases you might want to check if tab.id is not undefined before calling tabs.update.

That being said, I'm not sure in which cases tab.id is undefined.

**Comment by Lusito** [comment]
Well chrome at least talks about one case, where tab.id is undefined: when using the sessions API (i.e. already closed tabs)

**Comment by vitalets** [comment]
@Lusito thanks for your research!

**Comment by Lusito** [comment]
@vitalets I've released a new version, which fixes the issue.

**Comment by vitalets** [comment]
> @vitalets I've released a new version, which fixes the issue.

Thanks a lot! Could you share some details how you fix it?

**Comment by vitalets** [comment]
Awesome! 👍
