### ISSUE TITLE
Karma cannot find the package module

### ISSUE THREAD

**Issue by MishDish** [Lusito/webextension-polyfill-ts#15]
When running unit-tests , Karma is failing with the following error:
 `Uncaught Error: Can't find webextension-polyfill-ts [/node_modules/webextension-polyfill-ts/src/generated/index.ts]`.
However there is no problem when loading the module in the .ts files like this : 
`import { browser as browserWithPromise } from 'webextension-polyfill-ts';`.

**Comment by bhalperin** [comment]
Adding to above (I'm working with @MishDish):
In **package.json** we have `"webextension-polyfill-ts": "^0.8.9",` in `devDependencies` section.
Fails to load it in unit tests.

**Comment by Lusito** [comment]
Could you supply an example project which illustrates the issue?
I have mocha/chai in my unit tests for my extension https://github.com/lusito/forget-me-not and there all dependencies are devDependencies, so that shouldn't be any issue here.

I am targeting es2015 javascript as commonjs module, so maybe that is an issue here?
Also, I think someone mentioned on another project, that it would be better to export .d.ts files rather than ship the original .ts files, so that might be something I could look into as well.
But being able to reproduce this would help a lot.

**Comment by stormwin** [comment]
Hi @Lusito ,
Fix for this problem is exporting d.ts files.
I forked this project, added "declaration": true in ts.config,
changed "types": "src/generated/index.d.ts" to point d.ts in package.json and regenerate files again. 

You can see that in my fork at https://github.com/stormwin/webextension-polyfill-ts

If you want, i can create PR for this.

**Comment by Lusito** [comment]
Thanks. New version has been released.
