### ISSUE TITLE
Question: Why do you recommend installing as dev dependency?

### ISSUE THREAD

**Issue by avalanche1** [Lusito/webextension-polyfill-ts#19]

**Comment by Lusito** [comment]
Depending on what project you want to include it in, either dependency or devDependency might be more fitting. Since the most likely usecase is that you use it in a web extension, bundling it via webpack or similar, it seemed more like a devDependency to me, but adding it as dependency would work just as fine. Any reason for recommending non-dev as default?

**Comment by avalanche1** [comment]
Yep, I am working on an extension. And I use Parcel to bundle my typescript.
So which one sd I use? Dev or non-dev?

**Comment by Lusito** [comment]
It doesn't matter. Just add it like your other dependencies. So if you normally use `dependencies`, then keep using `dependencies`. Otherwise you can use `devDependencies`.

Parcel does not care how this dependency is added..
