### ISSUE TITLE
Question: how to handle differences between Chrome and Mozilla

### ISSUE THREAD

**Issue by davestewart** [Lusito/webextension-polyfill-ts#30]
Hey there,

I'm just converting a fairly complex extension to TypeScript, and I appreciate the effort you have put into this library!

My question is: do you have any thoughts on best practices between different browser flavours, now that TypeScript's strong typing is going to highlight differences between the APIs?

For example, Chrome's [tab update](https://developer.chrome.com/extensions/tabs#method-update) method:

```js
browser.tabs.update(someId, { autoDiscardable: false })
```
```
TS2345: Argument of type '{ autoDiscardable: boolean; }' is not assignable to parameter of type 'UpdateUpdatePropertiesType'.
```

The simple answer is to cast as `any` and the problem goes away, but do you have any better advice, plans for future versions, or other suggestions?

Is this the right library to develop Chrome extensions, or is this just something we have to cope with, with the newfound power that comes with TS?

Many thanks,
Dave

**Comment by Lusito** [comment]
Hi Dave,

I honestly have no extension published on the chrome store, but I do debug my extensions in chrome sometimes, since the debug tools are better. I do, however have to support multiple Firefox versions (desktop vs android and even vs different version numbers), which have varying support for the API.

#### Runtime checks
What I usually do is try to detect support in two different ways:

1. Check if the object is available. For example `if (browser.history) { ... }`
2. Use `browser.runtime.getBrowserInfo()` and then store a boolean map to reflect what is possible, for example like this:
https://github.com/Lusito/forget-me-not/blob/d67a7c58b6999258e8fe68b6ac2a6bd10d7a9f2d/src/shared/supportsInfo.ts#L42

#### Compile-time checks
If the TypeScript definitions are not compatible, then we should check if we can adjust them to work on all browsers.
Your case of autoDiscardable can be fixed. MDN [seems to know about the property](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update), so I can apply a manual fix on mozillas schemas before generating the types.

#### TL-DR
In theory this library is supposed to work for all browsers. In practice, however, I do not have the time to test the complete API with all browser-specific use-cases. So if you find type-incompatibilities, please report them and I'll see what can be done about it.

Cheers
Santo

**Comment by davestewart** [comment]
Hey Santo,

Thanks for fixing that, and great to make your acquaintance!

Not sure if you know, but the schema for the chromium project is available here:

- https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/api/schemas.md
- https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/api

I don't know if that is helpful to you.

I'd love to help out on the project, but looks like it would be a learning curve to understand what you've set up to build all this.

So, keep up the great work, and I'll report things as I find them in the mean time!

Thanks again,
Dave

**Comment by Lusito** [comment]
I use the mozilla schema files, since they are actually trying to support multiple browsers. Chrome only tries to support itself, so all of the goodies that Firefox brings to the table would be ignored.

The learning curve here is indeed an issue. Maybe I should write up some documentation to make contributions easier, but that's a lot of work as well and changes are rarely needed (see the issue count). Most of the time it's just running an npm command to fetch the latest schemas and publish a new version.

**Comment by davestewart** [comment]
> Chrome only tries to support itself, so all of the goodies that Firefox brings to the table would be ignored

Exactly. Perhaps there could / should be some kind of merging of schemas?

You could maybe even build for different browser versions?

```
import { browser } from 'webextension-polyfill-ts/chrome'
```

Just some ideas.

I'm working on a large chrome / cross-browser extension at the moment, so it would be in my interest to take an active / contributing interest in this project!

**Comment by Lusito** [comment]
The whole point of a polyfill is to use the same code for all browsers. importing from /chrome would be an antipattern in my opinion.

Merging of schemas might be possible, but that will be a very tricky thing to do right.

If you are serious about contributing, I can put up some more documentation about how the project works. Then you can read that, look at the code and write me if things are unclear or need more documentation. Does that sound good to you?

**Comment by davestewart** [comment]
I think that's a great idea!

It would be great if you would outline your ideas of why the library exists and what its aims should be as well.

Looking forward to it! (but no rush)

**Comment by Lusito** [comment]
So, here's a quick write-up: https://github.com/Lusito/webextension-polyfill-ts/blob/develop/internal.md

It's probably not perfect yet, but should give you a better idea of the whole project goals, the current implementation and its problems.

**Comment by Lusito** [comment]
Done some refactoring, code cleanup and code comments. It's now a lot less cluttered and should be easier to understand than before. Let me know if you have questions.

**Comment by davestewart** [comment]
Hey, great work!

I think it's probably always going to be a bit intimidating for anyone coming directly to the lib; quite a lot of knowledge needed: browser API, TypeScript internals, Node, design patterns etc, etc.

I will have to jump into it to get to understand it, but that time for won't be now, sadly. I'm months behind on a software release, and that is my first priority.

Have you tried to get in touch with any of the [contributors](https://github.com/mozilla/webextension-polyfill/graphs/contributors) of the mozilla library? I bet they would be stoked to see this.

**Comment by davestewart** [comment]
FYI a nice TS tute of the Visitor pattern popped up in my fees today. Might be nice to hyperlink it:

https://dev.to/alfki/the-visitor-pattern-exemplified-in-typescript-4cp5
