### ISSUE TITLE
broken on Chrome

### ISSUE THREAD

**Issue by akopchinskiy** [Lusito/webextension-polyfill-ts#33]
![image](https://user-images.githubusercontent.com/39277134/87880816-184b9b00-c9f5-11ea-8649-0bb600813048.png)
![image](https://user-images.githubusercontent.com/39277134/87880819-1da8e580-c9f5-11ea-9eb0-471f2e60086a.png)

**Comment by Lusito** [comment]
@akopchinskiy Sorry for the late reply.

Thanks for the report, but the code you are showing is actually from [webextension-polyfill](https://github.com/mozilla/webextension-polyfill), so if there is a bug, you'd have to report it there.

Since I can't reproduce that issue I would assume though, that you have an issue in your build-process, which possibly converts the class to something else.
