### ISSUE TITLE
Missing header listener option

### ISSUE THREAD

**Issue by Pyrodash** [Lusito/webextension-polyfill-ts#35]
'extraHeaders' is missing from WebRequest types OnBeforeRequestOptions, OnBeforeSendHeadersOptions, OnSendHeadersOptions, OnHeadersReceivedOptions, OnAuthRequiredOptions, OnResponseStartedOptions, OnBeforeRedirectOptions, OnCompletedOptions

It's available on chrome's [docs](https://developer.chrome.com/extensions/webRequest#type-OnBeforeRequestOptions).

**Comment by Lusito** [comment]
Hi @Pyrodash sorry for the late reply.

Thanks for the report. I've released a new version containing the fixes. Not sure if onErrorOccurredEvent is correctly defined though, since the chrome documentation is a bit confusing. I've taken the other events as example, so I'm positive that it **should** be correct.

Let me know if you have further issues.
