### ISSUE TITLE
Support for declarativeContent api

### ISSUE THREAD

**Issue by remon-nashid** [Lusito/webextension-polyfill-ts#37]
Unless I'm missing something, TS tells me that `Property 'declarativeContent' does not exist on type 'Browser'`, when I try to `browser.declarativeContent.onPageChanged.addRules([{`

I wonder if this API is in the roadmap, or perhaps if I could accomplish declarative content, differently.

Thanks!

**Comment by Lusito** [comment]
Declarativecontent api has not been implemented in firefox yet, which is why this isn't automatically added to this Project: https://bugzilla.mozilla.org/show_bug.cgi?id=1435864

This has to be manually defined using the fixes.json file. Will take a look when i get the time. Until then you can cast to any and use it without typesafety

**Comment by remon-nashid** [comment]
> Will take a look when i get the time. Until then you can cast to any and use it without typesafety

Thank you! That'll work for now.

**Comment by Lusito** [comment]
So, this was a bit hacky and it only works for chrome. So once Mozilla implements this and adds it to webextension-polyfill, I'm probably gonna have to adjust this a bit. Let me know if this works for you @remon-nashid .

**Comment by remon-nashid** [comment]
Thanks for accommodating my suggestion @Lusito! I'll give it a try shortly.
