### ISSUE TITLE
Adaptation to the WebExtensions Experiments API

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Lusito/webextension-polyfill-ts#40]
How do I prepare a project folder if I want to use experimental APIs made by myself with:
webextensions-experiments.readthedocs.io/
?

Where to add your own `*.d.ts` file, how to most efficiently generate it from your experimental schema file?

**Comment by Lusito** [comment]
Hi @lukaszpolowczyk , sorry about the delay.

Create a new file my-experiments.d.ts:
```typescript
import 'webextension-polyfill-ts';

declare module 'webextension-polyfill-ts' {
    interface Browser {
        foobar: string;
    }
}
```

Now the browser type has the foobar property on it (the type only).

If you want to generate your types, you'll need schema files for this. If you have them:
- Clone this repository
- Run `npm install`
- Run `npm run all`
- Copy your schema file into the schemas folder
- Run `npm run validate:schemas`
- Run `npm run build`

Now the lib folder should contain a file for your schemas. You can copy that into your project and reference it from the  file above instead of manually defining it.

This is theoretical. I haven't tried this.
