### ISSUE TITLE
Missing 'selected' property in Tabs.Tab

### ISSUE THREAD

**Issue by softoika** [Lusito/webextension-polyfill-ts#41]
There is no `selected` property in `Tabs.Tab`(See [/lib/tabs.d.ts](https://github.com/Lusito/webextension-polyfill-ts/blob/4814f784e9a101055c53ac724f9bfb26e5c13aed/lib/tabs.d.ts#L73)).
The `selected` property is [deprecated](https://developer.chrome.com/extensions/tabs#type-Tab) since Chrome 38, but I think this is necessary in the type for consistency with [chrome.tabs.Tab](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome/index.d.ts#L7126).

**Comment by Lusito** [comment]
The property is deprecated and there is an alternative available.
I'm skipping deprecated parts of the API on purpose, as they should not be used.

Consistency with the DefinitelyTyped project is not a goal of this project, so that's no reason.
Feel free to bring up arguments why you need this deprecated property to be available. Otherwise I'm gonna close this as "won't fix".

**Comment by softoika** [comment]
I agree to close this issue because I just want to assign `Tabs.Tab` value to `chrome.tabs.Tab`.
I'm using this library to use functions that return Promise, but I didn't know that the Chrome API event handlers (such as `chrome.tabs.onCreated`) could also be used from this library.
