### ISSUE TITLE
Missing API chrome.scripting from Manifest V3

### ISSUE THREAD

**Issue by C-n-o-Pack** [Lusito/webextension-polyfill-ts#58]
You can see changes here: https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/

**Comment by Lusito** [comment]
Thanks for the report. Theoretically fixed in 0.26.0. Let me know if you encounter issues.

**Comment by avalanche1** [comment]
@Lusito A more general question: is manifest v3 supported overall by this lib?
Because I couldn't find any mention of V3 in the vanilla webextension-polyfill docs

**Comment by Lusito** [comment]
@avalanche1 This lib supports everything that the mozilla schema defines or has been added by manual overrides. This should do most of the v3 changes. But I can't say 100% for sure since I don't use most of V3 yet. Sorry for the late reply, I didn't see the question after this was closed.

Why I came back: The official schemas now include the scripting API, but they are incomplete. I adjusted the code to take as much of the official schemas as possible and only extend what was missing. It should work fine with the next version, but if you encounter issues, let me know.

It will be available once this PR is merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57314
