### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by ferllings** [Lusito/webextension-polyfill-ts#82]
Hello,

I've been migrating from from webextension-polyfill-ts

With the @types/webextension-polyfill, I get this error:

```
in ./node_modules/webextension-polyfill/dist/browser-polyfill.js

Module parse failed: Unexpected token (25:25)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   "use strict";
|
>   if (!globalThis.chrome?.runtime?.id) {
|     throw new Error("This script should only be loaded in a browser extension.");
|   }

 @ ./src/main.ts 6:0-44 16:23-30
 @ multi ./src/main.ts
```

Do I miss something?

Thanks for your help

**Comment by Lusito** [comment]
Hi @ferllings, it looks like you are using the ES6 elvis-operator. Since you are using webpack, I'm guessing you are missing https://webpack.js.org/loaders/babel-loader/ or similar to have support for these.

Another possibility is, that babel is ignoring the node-modules folders here. See this: https://github.com/babel/babel-loader/issues/171

It seems that line has been added 2 months ago here: https://github.com/mozilla/webextension-polyfill/pull/377.
In any way, it's not related to the types (which is this projects only goal), so you're better off asking that question in the repo for the actual code: https://github.com/mozilla/webextension-polyfill/

**Comment by ferllings** [comment]
Thanks,
after updating few modules it builds without issue.
